### ISSUE TITLE
Add counts for distinct subjects and distinct objects in association queries

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/biolink-api#13]
association counts are trivially returned for any association query, even if pageination used.

For counts of distinct subjects and objects, we can't assume that `|Subject|=1` (consider intermediate disease as subject) or `|Object|=|Association|`

Options are:

 1. precompute ahead of time and populate solr with precomputed results
 2. utilize some function of solr I am not aware of
 3. iterate over all results and count

1 is not good as we would have to precompute for the cross-product of all query options

2 may require further investigation

3 will work fine for any subject query for which the subject is loosely-speaking entity level, with a predictably bounded number of associations. E.g. genes, specific diseases.

**Comment by cmungall** [comment]
@kshefchek can you point to the code that does this for monarch at the moment

**Comment by kshefchek** [comment]
Right now we facet over the field and then get the length of the facet list.  There might be a way to get the number directly in the solr document with solr 6.

See: https://github.com/monarch-initiative/monarch-app/blob/2624bc0d9/lib/monarch/api.js#L4236

**Comment by cmungall** [comment]
OK, great. I see this can be used to fetch a distinct list of ontology terms used to annotate the bioentity too

**Comment by kshefchek** [comment]
We can use the stats component to get the distinct count and total count without enumerating every subject/object if desired.

For example add the params to count objects:
stats=true&stats.field={!calcdistinct=true distinctValues=false count=true}object

https://lucene.apache.org/solr/guide/6_6/the-stats-component.html

This should work on pivot tables as well.

**Comment by kshefchek** [comment]
Here is an example of using this on a pivot table (top level mondo ID):

https://solr.monarchinitiative.org/solr/golr/select/?defType=edismax&qt=standard&indent=on&wt=json&rows=0&start=0&fl=*,score&facet=true&facet.mincount=1&json.nl=arrarr&facet.limit=20&facet.method=enum&fq=object_closure:%22MONDO:0000001%22&q=*:*&stats=true&stats.field={!tag=piv1%20calcdistinct=true%20distinctValues=false}subject&facet.pivot={!stats=piv1}subject_category,subject&f.subject.facet.limit=0

Note we still need to make two calls since IDs may be the subject or object, but this is an improvement over the N calls with currently do in monarch (N = the number of tabs)

**Comment by cmungall** [comment]
This is great

@deepakunni3 - note that we still use solr3 for go, I suspect that doesn't work here
